### ISSUE TITLE
Create the indexes from gitee

### ISSUE THREAD

**Issue by bluejeams** [grimoirelab-gitee/grimoirelab-elk-gitee#7]
Reading from https://chaoss.github.io/grimoirelab-tutorial/gelk/simple.html to create the indexes in ElasticSearch:

(gl) $ p2o.py --enrich --index git_raw --index-enrich git \
  -e http://localhost:9200 --no_inc --debug \
  git https://github.com/grimoirelab/perceval.git

so how to use use this module to create the indexes from those data retrieved from gitee？

**Comment by eyehwan** [comment]
We have wiki here:
https://github.com/grimoirelab-gitee/grimoirelab/wiki/How-to-run-grimoirelab-gitee%3F
Let me know if there was anything unclear.

**Comment by shanchenqi** [comment]
Do you have further requirements? Otherwise, we will close it tomorrow.
